search:
  Training\Bundle\UserNamingBundle\Entity\UserNamingType:
    alias:                          training_user_naming_type
    search_template:                '@TrainingUserNaming/UserNamingType/Search/resultRow.html.twig'
    route:
      name:                       training_user_naming_type_view
      parameters:
        id:                     id
    fields:
      -
        name:                   title
        target_type:            text
        target_fields:          [title]
